"""The ``j``-resolved projection against ``projwfc.x`` (spinor P8).

``projwfc.x`` reaches this through ``atomic_wfc_nc_proj``, which asks
``atomic_wfc_acc`` for ``starting_spin_angle = .TRUE.`` -- the spin-angle
functions ``|l j m_j>`` themselves, where a noncollinear SCF and DFT+U take the
``j``-averaged up/down set. The reference is generated by
``tools/generate_reference.py`` (stems ``pt-soc`` and ``pt-soc-paw``) and stored
beside the input.

**The reference must be unsymmetrised and ``nosym`` in the `pw.x` input is not
enough.** ``projwfc.x`` re-derives the point group rather than inheriting the one
the SCF ran with, so ``lsym = .true.`` symmetrises even where ``pw.x`` printed
"No symmetry found"; measured on ``pt-soc``, it averages the two Kramers partners
of the ``6S`` shell to 0.495 each where the raw projection is 0.870/0.120. The
Loewdin charges and the spilling are identical either way, so only a
per-column comparison can see it.

**What is compared, and why not the raw per-band projection.** An individual
``|<phi_i|S|psi_n>|^2`` is not invariant under the unitary mixing a degenerate
eigensolver is free in, and a spinor band structure is Kramers-degenerate
everywhere -- so the comparable quantities are the multiplet sums and the
occupation-weighted charges. Both are checked. The *empty* bands are excluded
rather than accommodated: above the Fermi level the two codes' states are not
converged to each other at all, and on this cell that is worth 0.52 in a raw
projection and nothing in any occupied quantity.
"""

import re

import numpy as np
import pytest

from defumat import Calculator
from defumat.projwfc.projections import atomic_projections, calculation_channels
from defumat.workflows.pdos import lowdin_charges
from defumat.units import RY_TO_EV

pytestmark = pytest.mark.regression

def _occupied(scf) -> int:
    """How many bands carry weight, derived rather than written down.

    A spinor band holds one electron and this is a smeared metal, so the count
    is "every band with a non-negligible occupation anywhere in the zone" rather
    than ``nelec``. Derived so that a change of ``nbnd`` or ``degauss`` moves the
    check with the physics instead of silently comparing empty bands, whose
    states the two codes do not converge to each other at all.
    """
    occupations = np.asarray(scf.occupations)
    occupations = occupations.reshape(occupations.shape[-2:])
    weights = np.asarray(scf.occupations)  # occupations are already wg
    per_band = np.abs(occupations).max(axis=0)
    return int(np.count_nonzero(per_band > 1.0e-3 * per_band.max()))


def _read_filproj(path):
    """``projwfc.x``'s ``filproj``: ``(labels, proj[nwfc, nbnd, nk])``.

    Ten decimals, against the three the standard output rounds to -- which is
    what a column-by-column comparison needs. The block order is ``nwfc``, then
    ``ik`` slow and ``ibnd`` fast.
    """
    lines = path.read_text().splitlines()
    index = 0
    while True:
        parts = lines[index].split()
        if len(parts) == 3 and all(p.lstrip("-").isdigit() for p in parts):
            natomwfc, nk, nbnd = map(int, parts)
            break
        index += 1
    index += 2  # the "T T" line
    labels, proj = [], np.zeros((natomwfc, nbnd, nk))
    for column in range(natomwfc):
        labels.append(lines[index].split())
        index += 1
        for _ in range(nk * nbnd):
            ik, ibnd, value = lines[index].split()
            proj[column, int(ibnd) - 1, int(ik) - 1] = float(value)
            index += 1
    return labels, proj


def _read_kresolved(path):
    """QE's ``kresolveddos`` output: ``(energies_eV, columns[nk, nE, ncol])``.

    One block per k-point, separated by a blank line. **The weights are not in
    the file**: ``partialdos.f90`` sets ``wkeff = 1`` under ``kresolveddos``
    ("set equal weight to all k-points"), so a caller wanting the k-summed curve
    QE would otherwise have written has to apply ``wk`` itself. Reading it
    unweighted and summing is a factor of ``nk`` wrong and still looks like a
    density of states.
    """
    blocks, current = [], []
    for line in path.read_text().splitlines():
        if line.startswith("#"):
            continue
        if not line.strip():
            if current:
                blocks.append(current)
                current = []
            continue
        current.append([float(value) for value in line.split()])
    if current:
        blocks.append(current)
    data = np.asarray(blocks)                    # (nk, nE, 2 + ncol)
    return data[0, :, 1], data[:, :, 2:]


def _qe_lowdin(text):
    charges = {
        match.group(2): float(match.group(3))
        for match in re.finditer(
            r"total charge =\s*([\d.]+),\s*([spdf]) =\s*([\d.]+)", text
        )
    }
    return (
        charges,
        float(re.search(r"total charge =\s*([\d.]+)", text).group(1)),
        float(re.search(r"Spilling Parameter:\s*([\d.]+)", text).group(1)),
    )


@pytest.fixture(scope="module")
def _projection(request):
    """The SCF, the projection and the reference for one case."""
    stem, case = request.param
    root = request.config.rootpath
    filproj = root / "tests/data/qe" / f"reference.{stem}.projwfc_up"
    stdout = root / "tests/data/qe" / f"reference.projwfc.{stem}"
    if not filproj.is_file():
        pytest.skip(f"{stem}: no generated reference (needs projwfc.x)")

    labels, reference = _read_filproj(filproj)
    calculator = Calculator.from_file(
        root / "tests/data/qe" / f"{case}.in", pseudo_dir=root / "tests/data/pseudo"
    )
    scf = calculator.get_scf()
    calculation = calculator.calculation
    states = np.asarray(scf.wavefunctions)
    states = states.reshape((1,) + states.shape[-3:])
    projections = np.asarray(
        atomic_projections(calculation, states, symmetrize=False)
    )  # (1, nk, natomwfc, nbnd)
    return {
        "labels": labels,
        "reference": reference,
        "ours": np.transpose(projections[0], (1, 2, 0)),  # (nwfc, nbnd, nk)
        "projections": projections,
        "channels": calculation_channels(calculation),
        "calculation": calculation,
        "scf": scf,
        "stdout": stdout.read_text(),
    }


def _cases(*names):
    return pytest.mark.parametrize(
        "_projection", names, indirect=True,
        ids=[stem for stem, _ in names],
    )


PAW = ("pt-soc-paw", "pt-soc-paw-nosym")


@_cases(PAW)
def test_the_columns_are_the_ones_projwfc_builds(_projection):
    """``natomwfc``, and each column's ``(l, j, m_j)``, against ``fill_nlmchi``.

    ``filproj``'s header names every column, so this is QE's own label table
    rather than a restatement of it. Platinum's PAW dataset has five shells --
    ``6S(1/2)``, ``6P(1/2)``, ``6P(3/2)``, ``5D(3/2)``, ``5D(5/2)`` -- and 18
    columns, where the scalar count is 9.
    """
    labels, channels = _projection["labels"], _projection["channels"]
    assert len(labels) == len(channels)
    for label, channel in zip(labels, channels):
        # "<nwfc> <na> <atm> <els> <n> <l> <j> <m_j>"
        assert int(label[5]) == channel.l
        assert float(label[6]) == pytest.approx(channel.j)
        assert float(label[7]) == pytest.approx(channel.mj)


@_cases(PAW)
def test_the_occupied_multiplet_sums_match_projwfc(_projection):
    """The invariant: a degenerate multiplet's projection, summed over its bands.

    Blind to the rotation the two eigensolvers are each free in, which the raw
    per-band projection is not.
    """
    reference, ours = _projection["reference"], _projection["ours"]
    eigenvalues = np.asarray(_projection["scf"].eigenvalues)
    eigenvalues = eigenvalues.reshape(eigenvalues.shape[-2:])

    occupied = _occupied(_projection["scf"])
    assert 8 <= occupied <= eigenvalues.shape[1], occupied

    worst = 0.0
    for ik in range(eigenvalues.shape[0]):
        energies, start = eigenvalues[ik], 0
        for band in range(1, occupied + 1):
            if band == occupied or abs(energies[band] - energies[start]) > 1.0e-5:
                worst = max(worst, np.abs(
                    reference[:, start:band, ik].sum(1) - ours[:, start:band, ik].sum(1)
                ).max())
                start = band
    assert worst < 1.0e-4


@_cases(PAW)
def test_the_lowdin_charges_match_every_digit_projwfc_prints(_projection):
    """``print_lowdin``'s block: the charge on each ``l`` and the spilling.

    This is the strongest number here, because it exercises the whole chain --
    the spin-angle orbitals, the ``S`` metric with ``qq_so``, the Loewdin
    orthogonalisation over all ``natomwfc``, and the grouping of the two ``j``
    shells back onto one ``l``.
    """
    calculation, scf = _projection["calculation"], _projection["scf"]
    eigenvalues = np.asarray(scf.eigenvalues)
    occupations = np.asarray(scf.occupations).reshape(
        (1,) + eigenvalues.shape[-2:]
    )
    charges = lowdin_charges(
        _projection["projections"], occupations, _projection["channels"],
        calculation.system.structure.nat, calculation.nelec,
    )
    reference, total, spilling = _qe_lowdin(_projection["stdout"])
    ours = np.asarray(charges.charges)[0]
    for l, label in enumerate("spd"):
        assert ours[l] == pytest.approx(reference[label], abs=5.0e-5)
    assert ours.sum() == pytest.approx(total, abs=5.0e-5)
    assert charges.spilling == pytest.approx(spilling, abs=5.0e-5)


@_cases(PAW)
def test_a_spinor_projection_has_no_m_resolved_charge(_projection):
    """``print_lowdin`` allocates ``charges_lm`` only ``IF ( nspin /= 4 )``.

    A spin-angle function has an ``m_j`` and no ``m``, so there is no ``p_x``
    weight to report; ``None`` rather than an array that would index without
    meaning anything.
    """
    calculation, scf = _projection["calculation"], _projection["scf"]
    occupations = np.asarray(scf.occupations).reshape(
        (1,) + np.asarray(scf.eigenvalues).shape[-2:]
    )
    charges = lowdin_charges(
        _projection["projections"], occupations, _projection["channels"],
        calculation.system.structure.nat, calculation.nelec,
    )
    assert charges.charges_lm is None
    assert charges.charges_lm_by_spin is None
    assert "Spilling" in charges.format()  # still formats


def test_a_symmetrised_spinor_projection_is_refused(qe_testsuite, pseudo_dir):
    """``sym_proj_so`` needs the SU(2) representation of each operation.

    Refused rather than approximated by averaging the ``m`` indices alone, which
    would mix ``m_j`` across a spin frame that the operation has turned. Checked
    on ``pw_spinorbit/spinorbit.in``, which keeps its symmetry -- the cases above
    run ``nosym``, where there is correctly nothing to refuse over and the guard
    must *not* fire.

    The refusal is made before the states are touched, so no SCF is run here.
    """
    calculator = Calculator.from_file(
        qe_testsuite / "pw_spinorbit" / "spinorbit.in", pseudo_dir=pseudo_dir
    )
    calculation = calculator.calculation
    assert calculation.use_symmetry and calculation.symmetries.nsym > 1
    states = np.zeros((1, calculation.system.kpoints.nk, 1,
                       2 * calculation.basis.planewaves.npwx), dtype=complex)
    with pytest.raises(NotImplementedError, match="sym_proj_so"):
        atomic_projections(calculation, states, symmetrize=True)


@_cases(PAW)
def test_an_unsymmetrised_projection_is_allowed_on_a_nosym_run(_projection):
    """The other half of the same guard: ``nosym`` must not trip it.

    ``symmetrize`` is and-ed with ``use_symmetry``, so the default
    ``symmetrize=True`` is what a caller gets and it has to work here -- a
    refusal that fired on the supported path would make the feature unreachable
    by its own escape route.
    """
    calculation = _projection["calculation"]
    states = np.asarray(_projection["scf"].wavefunctions)
    states = states.reshape((1,) + states.shape[-3:])
    projections = np.asarray(atomic_projections(calculation, states))
    assert np.allclose(projections, _projection["projections"])



# --------------------------------------------------------------------------
# The curves, which is the workflow rather than the projection
# --------------------------------------------------------------------------

@pytest.fixture(scope="module")
def _curves(request):
    """``run_pdos`` on the grid and the smearing ``projwfc.x`` used."""
    root = request.config.rootpath
    cases = root / "tests/data/qe"
    total = cases / "reference.pt-soc-paw.pdos_tot"
    if not total.is_file():
        pytest.skip("pt-soc-paw: no generated reference (needs projwfc.x)")

    energies, _ = _read_kresolved(total)
    calculator = Calculator.from_file(
        cases / "pt-soc-paw-nosym.in", pseudo_dir=root / "tests/data/pseudo"
    )
    scf = calculator.get_scf()
    # ``DeltaE = 0.05`` eV from ``tools/generate_reference.py``; the broadening
    # is the *run's* own, which ``projwfc.x`` reads off the file and prints as
    # "ngauss,degauss= 1 0.020000" -- Methfessel-Paxton, not a gaussian, so the
    # curves go negative on the wings and a gaussian would not reproduce them.
    pdos = calculator.get_pdos(
        scheme="mp", degauss=0.02, delta_e=0.05 / RY_TO_EV,
        emin=energies[0] / RY_TO_EV, emax=energies[-1] / RY_TO_EV,
    )
    eigenvalues = np.asarray(scf.eigenvalues)
    eigenvalues = eigenvalues.reshape(eigenvalues.shape[-2:])
    # Everything below the lowest *empty* band, less five smearing widths so
    # that no unconverged state contributes even through the tail of its delta.
    edge = eigenvalues[:, _occupied(scf):].min() * RY_TO_EV - 5 * 0.02 * RY_TO_EV
    return {
        "cases": cases,
        "energies": energies,
        "window": energies <= edge,
        "weights": np.asarray(calculator.calculation.system.kpoints.weights),
        "pdos": pdos,
        "n": energies.size,
    }


def test_the_total_curve_matches_projwfc(_curves):
    """The workflow's output, not the projection it is built from.

    Compared where both codes' states are converged. Above that the topmost
    bands are the ones neither eigensolver converges -- they are the same six
    states in a different place, and the curves separate by 15 per cent of the
    peak there while agreeing to a sixth of a per cent below it.
    """
    _, columns = _read_kresolved(_curves["cases"] / "reference.pt-soc-paw.pdos_tot")
    theirs = (columns[:, :, 0] * _curves["weights"][:, None]).sum(axis=0)
    ours = _curves["pdos"].total.total_dos[:_curves["n"]] / RY_TO_EV

    window = _curves["window"]
    assert window.sum() > 300
    worst = np.abs(ours - theirs)[window].max()
    assert worst < 2.0e-2 * theirs[window].max(), worst


def test_every_shell_curve_matches_projwfc(_curves):
    """One file per ``(atom, wfc, l, j)``, compared on its ``ldos`` column.

    The shell's own sum rather than its ``m_j`` columns, which is the same
    invariance the Loewdin comparison rests on: a rotation inside a degenerate
    multiplet moves weight between the columns and not between the files.
    """
    pdos, window = _curves["pdos"], _curves["window"]
    files = sorted(_curves["cases"].glob("reference.pt-soc-paw.pdos_atm*"))
    assert len(files) == 5, [f.name for f in files]

    for path in files:
        _, columns = _read_kresolved(path)
        theirs = (columns[:, :, 0] * _curves["weights"][:, None]).sum(axis=0)
        letter, j = path.name.split("(")[-1].rstrip(")").split("_j")
        ours = sum(pdos.pdos[c.index] for c in pdos.channels
                   if c.l_label == letter and abs(c.j - float(j)) < 1.0e-6)
        ours = ours[:_curves["n"]] / RY_TO_EV
        worst = np.abs(ours - theirs)[window].max()
        assert worst < 2.0e-2 * theirs[window].max(), (path.name, worst)
