"""P46 check: the force and the stress of a noncollinear or spin-orbit run.

The functional in :mod:`defumat.forces.energy` grew a spinor branch, so
``noncolin = .true.`` -- with or without ``lspinorb`` -- has forces, a stress
and therefore a relaxation, where it had a refusal. What changed is two
quadratic forms and a layout, and this file is arranged around measuring them
one at a time:

* the **energy identity** first, because it is the check that the functional is
  the total energy before anything differentiates it. A spinor's coefficients
  are one vector of length ``2 npwx`` rather than two states, and the kinetic
  term reads ``state_kinetic`` for that reason; the nonlocal term takes the
  complex 2x2-in-spin ``dvan_so`` where a collinear run takes ``dij``, and the
  orthonormality constraint takes ``qq_so`` where it takes ``qq``. Any of the
  three wrong shows up here, at the fixed point, before a derivative is
  involved.
* the **finite difference** of that same frozen energy under a displacement,
  which isolates the gradient from every other thing that could be wrong. It is
  P39's anchor and it needs no Fortran at all.
* the **sum rule**, which is run and is *not* rested on: an atom sum is blind to
  a transfer between atoms, which is exactly how P28a's ``abs`` trap survived
  two identities.
* and only then **`pw.x`**, which computes both quantities for a spinor run.

The cases, each adding one thing:

``h4-noncolin-force``
    four hydrogens in a chain, each moment turned 90 degrees from the one
    before, one atom displaced. Norm-conserving, ``nspin_mag = 4``, ``nosym``:
    the magnetization is a genuine vector field and ``S`` is the identity, so
    the force is pure Hellmann-Feynman through ``dvan_so``.
``pt2-soc-force`` and ``pt2-soc-paw-force``
    ``pw_spinorbit/spinorbit.in``'s fcc platinum in a cell doubled along ``a1``
    with one atom pushed 0.32 bohr off its site, on the fully-relativistic
    **ultrasoft** and **PAW** datasets. ``lspinorb``, ``nspin_mag = 1``, and an
    augmentation charge -- so the constraint term carries ``qq_so`` and there is
    a Pulay force, which ``h4-noncolin-force`` cannot test, its H.pz-vbc having
    no augmentation charge at all. The k-grid is unshifted and reduces 32 points
    to 14, which is the genuine wedge the symmetrisation check needs, and the
    two atoms leave a stress with off-diagonal entries rather than the isotropic
    one a one-atom cell gives.
``pw_spinorbit/spinorbit*``
    QE's own one-atom fcc platinum, which asks for ``tstress`` and therefore
    supplies a *stress* reference for an ultrasoft, a PBE and a PAW spin-orbit
    run with nothing new having to be generated. Its force is zero by symmetry,
    so only the stress is compared.
"""

from functools import lru_cache
from pathlib import Path

import numpy as np
import pytest
import jax
import jax.numpy as jnp

from defumat.forces import compute_forces
from defumat.forces.energy import energy_at, state_from_result
from defumat.io import read_qe_output
from defumat.io.pwin import read_pw_input
from defumat.pseudo import read_upf
from defumat.scf import Calculation, run_scf
from defumat.stress import compute_stress
from defumat.system import build_system
from defumat.workflows.relax import run_relax
from tests.tolerances import FORCE_RY_BOHR, STRESS_RY_BOHR3, TOTAL_ENERGY_RY

#: How close the two relaxed atoms must come to being half a cell apart, in
#: crystal coordinates of the doubled cell. 0.001 is 0.015 bohr; achieved 5.5e-5.
RELAX_POSITION = 1.0e-3

#: How far the **unsymmetrised** force must break the crystal's ``F_x = -F_z``
#: for the symmetrised assertion beside it to mean anything, in Ry/bohr. A
#: **lower** bound, not a tolerance.
#:
#: A wedge sum is exact for a scalar and not for a vector, so the raw gradient
#: is not a symmetric object and is not expected to be. Measured: **1.1185e-2
#: Ry/bohr on forces of 5.2432e-2** for the ultrasoft case (21.3 per cent) and
#: **3.8661e-3 on 5.9167e-2** for the PAW one (6.5 per cent), both of which are
#: set by which representatives the 14-point wedge picked out of the 32-point
#: grid rather than by any accuracy. 1e-3 clears the smaller of the two by a
#: factor of four and sits four decades above the 3.5e-7 the wedge and the
#: closed grid agree to once both *are* symmetrised.
WEDGE_ASYMMETRY_FLOOR = 1.0e-3

pytestmark = [pytest.mark.regression, pytest.mark.slow]

CASES = Path(__file__).resolve().parents[1] / "data" / "qe"

#: ``(case, input path relative to nothing, reference stem)``. The platinum
#: cases live in QE's own test-suite and their references were regenerated by
#: ``tools/generate_reference.py`` under the ``<directory>-<stem>`` convention.
LOCAL_CASES = ["h4-noncolin-force", "pt2-soc-force", "pt2-soc-paw-force"]
PLATINUM = ["spinorbit", "spinorbit-pbe", "spinorbit-paw"]


@pytest.fixture(autouse=True)
def _drop_compiled_code():
    """Drop XLA's compiled executables between cases, as ``test_ten_site`` does.

    This file runs seven cells that share no shape -- a four-atom hydrogen
    chain, three platinum cases and QE's own three ``pw_spinorbit`` inputs --
    so each one compiles the whole SCF *and* the gradient stack afresh and the
    backend keeps every executable for the life of the process. Together with
    an unbounded ``_converged`` (spinor wavefunctions, two components each)
    that took the file to 27 GB of a 30 GB machine and got it killed. The
    diagnosis and the fix are ``PLAN.md`` P28b's, one file over; the results
    stay cached and only the code is dropped.
    """
    yield
    jax.clear_caches()


@lru_cache(maxsize=2)
def _converged(path: Path, pseudo_dir: Path):
    system = build_system(read_pw_input(path))
    pseudos = tuple(read_upf(pseudo_dir / s.pseudo_file) for s in system.structure.species)
    calculation = Calculation(system, pseudos)
    result = run_scf(system, pseudos, calculation=calculation, conv_thr=1e-12,
                     max_iterations=250)
    return system, calculation, result


def _platinum(stem: str, qe_testsuite: Path, pseudo_dir: Path):
    path = qe_testsuite / "pw_spinorbit" / f"{stem}.in"
    if not path.is_file():
        pytest.skip("QE test-suite not present")
    reference = CASES / f"reference.out.pw_spinorbit-{stem}"
    if not reference.is_file():
        pytest.skip(f"no generated reference for {stem}")
    return _converged(path, pseudo_dir), read_qe_output(reference)


def _reference(case: str):
    path = CASES / f"reference.out.{case}"
    if not path.is_file():
        pytest.skip(f"no generated reference for {case}; run tools/generate_reference.py")
    return read_qe_output(path)


# --- the identity, before any derivative -------------------------------------

@pytest.mark.parametrize("case", LOCAL_CASES)
def test_the_frozen_energy_is_the_total_energy(case, pseudo_dir):
    """``energy_at`` at the converged geometry *is* the SCF total.

    The only check there is on the terms that do not move -- and the one that
    catches a ``dvan_so`` used where ``deeq_nc`` was meant, which would double
    count ``int V_eff Q_ij`` and be invisible in a force whose reference is a
    finite difference of the same wrong functional.
    """
    _, calculation, result = _converged(CASES / f"{case}.in", pseudo_dir)
    state = state_from_result(result)
    assert calculation.noncolin
    energy = float(energy_at(calculation, state, spinors=True))
    # Achieved 4.4e-16 (norm-conserving), 2.8e-14 (ultrasoft) and 9.9e-10
    # (PAW). The PAW figure is the radial one-centre quadrature, not the spinor
    # branch: a collinear PAW run has the same gap.
    assert energy == pytest.approx(result.total_energy, abs=1e-8)


@pytest.mark.parametrize("stem", PLATINUM)
def test_the_frozen_energy_is_the_total_energy_on_platinum(stem, qe_testsuite, pseudo_dir):
    """The same identity on ultrasoft, PBE and PAW spin-orbit datasets.

    PAW is the loosest of the three (7.5e-10 Ry against 1.4e-14), and that is
    the radial one-centre quadrature rather than the spinor branch: the same
    gap is there for a collinear PAW run.
    """
    (_, calculation, result), _ = _platinum(stem, qe_testsuite, pseudo_dir)
    state = state_from_result(result)
    energy = float(energy_at(calculation, state, spinors=True))
    assert energy == pytest.approx(result.total_energy, abs=1e-8)


# --- the QE-free anchor ------------------------------------------------------

def test_the_force_is_a_finite_difference_of_the_frozen_energy(pseudo_dir):
    """The anchor that shares nothing with `pw.x`, on the ``nosym`` chain.

    A central difference of :func:`~defumat.forces.energy.energy_at` under a
    displacement, against ``jax.grad`` of the same function. It isolates the
    gradient from the symmetrisation, the translation correction and QE's
    ``force_corr`` all at once, which is why it comes before the reference
    comparison rather than after it.
    """
    system, calculation, result = _converged(
        CASES / "h4-noncolin-force.in", pseudo_dir
    )
    state = state_from_result(result)
    positions = np.asarray(system.structure.positions, dtype=float)

    forces = compute_forces(calculation, result).forces
    step = 1.0e-3
    difference = np.zeros_like(positions)
    for atom in range(positions.shape[0]):
        for axis in range(3):
            plus = positions.copy()
            plus[atom, axis] += step
            minus = positions.copy()
            minus[atom, axis] -= step
            difference[atom, axis] = -(
                float(energy_at(calculation.at_positions(jnp.asarray(plus)),
                                state, spinors=True))
                - float(energy_at(calculation.at_positions(jnp.asarray(minus)),
                                  state, spinors=True))
            ) / (2.0 * step)

    # Achieved 6.2e-9 Ry/bohr on forces of 2.2e-2, which is the difference's own
    # floor at this step; the bound is set an order above it.
    assert np.abs(forces - difference).max() < 1e-7


def test_the_forces_sum_to_zero(pseudo_dir):
    """``sumfor``. Run, and deliberately not rested on.

    Translating the whole crystal cannot change its energy, so the residue is
    the error the FFT grid and the cutoff make. It is a *diagnostic*: an atom sum
    cannot see a transfer between atoms, which is how P28a's ``abs`` trap
    survived two identities. Achieved 1.3e-7 Ry/bohr against forces of 2.2e-2.
    """
    _, calculation, result = _converged(CASES / "h4-noncolin-force.in", pseudo_dir)
    forces = compute_forces(calculation, result)
    assert np.abs(forces.total_before_correction).max() < 1e-6


# --- against pw.x ------------------------------------------------------------

@pytest.mark.parametrize("case", LOCAL_CASES)
def test_forces_match_quantum_espresso(case, pseudo_dir):
    _, calculation, result = _converged(CASES / f"{case}.in", pseudo_dir)
    reference = _reference(case)
    assert result.total_energy == pytest.approx(
        reference.total_energy, abs=TOTAL_ENERGY_RY
    )
    forces = compute_forces(calculation, result)
    assert np.abs(forces.forces - reference.forces).max() < FORCE_RY_BOHR


@pytest.mark.parametrize("case", LOCAL_CASES)
def test_stress_matches_quantum_espresso(case, pseudo_dir):
    _, calculation, result = _converged(CASES / f"{case}.in", pseudo_dir)
    reference = _reference(case)
    stress = compute_stress(calculation, result)
    assert np.abs(stress.tensor - reference.stress).max() < STRESS_RY_BOHR3


@pytest.mark.parametrize("stem", PLATINUM)
def test_platinum_stress_matches_quantum_espresso(stem, qe_testsuite, pseudo_dir):
    """The stress of an ultrasoft, a PBE and a PAW spin-orbit run.

    QE's own ``pw_spinorbit`` inputs carry ``tstress = .true.``, so this needs no
    reference of its own. Achieved 9.8e-8 (ultrasoft LDA), 4.4e-7 (PBE) and the
    PAW figure in `PLAN.md` P46.
    """
    (_, calculation, result), reference = _platinum(stem, qe_testsuite, pseudo_dir)
    stress = compute_stress(calculation, result)
    assert np.abs(stress.tensor - reference.stress).max() < STRESS_RY_BOHR3


@pytest.mark.parametrize("case", ["pt2-soc-force", "pt2-soc-paw-force"])
def test_the_symmetrisation_reaches_the_crystals_invariant_subspace(case, pseudo_dir):
    """``F_x = -F_z`` on the displaced platinum, and proof the projection did it.

    The doubled cell's surviving operation exchanges ``x`` and ``z`` with a
    sign, so the force is constrained to that plane. ``compute_forces`` ends in
    ``symvector``, which projects onto exactly that subspace -- **so asserting
    the identity afterwards cannot fail**, and on its own it is
    ``CLAUDE.md``'s "a check whose null result cannot be told from a pass".
    That is ``OPEN.md`` C1.

    **The fix C1 proposed does not work, and the measurement is the finding.**
    It asked for the identity on the *unsymmetrised* gradient, "where it is a
    claim rather than a tautology". It is not a claim there either: a wedge sum
    is exact for a scalar and not for a vector, which is why ``symvector`` is
    not optional in the first place, so the raw gradient carries a
    symmetry-forbidden part by construction. Measured, it breaks ``F_x = -F_z``
    by **1.1185e-2 Ry/bohr on forces of 5.2432e-2** (ultrasoft, 21.3 per cent)
    and **3.8661e-3 on 5.9167e-2** (PAW, 6.5 per cent), set by which
    representatives the 14-point wedge picked out of the 32-point grid. A bound
    loose enough to pass that would discriminate nothing at all.

    So the test asserts the **pair**, which is a statement where neither half
    is: the projection had real work to do here, and it finished it -- to
    6.9e-18 on both datasets. What it cannot do is see a P46 term wrong by a
    factor the symmetry respects -- a dropped ``dvan_so`` or ``qq_so`` piece, a
    mis-scaled augmentation force. Those change the force's *magnitude* inside
    the invariant subspace, and what catches them is
    ``test_forces_match_quantum_espresso`` and
    ``test_the_force_is_a_finite_difference_of_the_frozen_energy``.

    **This case needs more than the runner's default cap**, which is worth
    knowing before it is discovered by a kill -- two were spent finding it.
    Alone in a fresh process the ultrasoft case peaks at **7,691 MB** and the
    PAW one at **12,204 MB**, already over ``tools/run_regression.sh``'s 12G
    default; the two parameters *together* in one process peak at **16,961
    MB**, because the backend keeps both cells' executables. So the file wants
    ``DEFUMAT_TEST_MEM_MAX=20G``, and the cost is ``Q_ij(G)`` at ``nh = 34`` in
    the backward pass -- the figure ``PLAN.md`` P46 already names for a
    fully-relativistic dataset.
    """
    _, calculation, result = _converged(CASES / f"{case}.in", pseudo_dir)
    forces = compute_forces(calculation, result)

    # The projection had something to do: without this line the next one is a
    # tautology and would pass against a ``symvector`` that ran on an already
    # symmetric gradient.
    raw = forces.unsymmetrized
    assert np.abs(raw[:, 0] + raw[:, 2]).max() > WEDGE_ASYMMETRY_FLOOR

    # And it finished it, which is also the check on ``atom_mapping``.
    assert np.abs(forces.forces[:, 0] + forces.forces[:, 2]).max() < 1e-12


# --- the symmetrisation ------------------------------------------------------

@lru_cache(maxsize=1)
def _platinum_nosym(pseudo_dir: Path):
    """The same cell on the whole closed grid, with no symmetry at all."""
    data = read_pw_input(CASES / "pt2-soc-force.in")
    data.namelists["system"]["nosym"] = True
    data.namelists["system"]["noinv"] = True
    system = build_system(data)
    pseudos = tuple(read_upf(pseudo_dir / s.pseudo_file) for s in system.structure.species)
    calculation = Calculation(system, pseudos)
    result = run_scf(system, pseudos, calculation=calculation, conv_thr=1e-12,
                     max_iterations=250)
    return system, calculation, result


def test_the_wedge_reproduces_the_closed_grid(pseudo_dir):
    """A force on a reduced k-set is a polar vector and must be symmetrised.

    ``compute_forces`` ends in ``symvector`` with
    :attr:`Calculation.symmetries`, which for ``nspin_mag = 4`` is already
    ``sgam_at_mag``'s magnetic group (P17) -- so the reuse is the whole of the
    implementation, and this is the only check on it. The comparison is against
    the *same cell* with ``nosym`` on all 32 points of an unshifted grid, which
    is closed under the point group and therefore needs no symmetrisation at
    all. Achieved 3.5e-7 Ry/bohr on the force and 3.5e-9 Ry/bohr^3 on the
    stress, with the two SCF totals 2.6e-13 Ry apart.

    **This check is what pins ``conv_thr`` at 1e-12 rather than 1e-10, and the
    reason is the starting guess.** A fully-relativistic dataset is seeded with
    the spin-angle functions topped up with *random* vectors, exactly as
    ``wfcinit`` does it, so these two runs do not start from the same span --
    they have different k-sets and the random part differs with them. At 1e-10
    that survives into the force as 6.9e-6 and this test fails; at 1e-12 it is
    3.5e-7. The number to compare against is ``pw.x``'s own, which is **4e-7**
    between the same two k-sets on this cell (measured, its symmetrised run
    against its ``nosym`` one), so a floor of a few times 1e-7 is the physics
    and not a slack tolerance -- QE does no better, because it seeds the same
    way.
    """
    _, wedge_calculation, wedge_result = _converged(
        CASES / "pt2-soc-force.in", pseudo_dir
    )
    _, full_calculation, full_result = _platinum_nosym(pseudo_dir)
    assert wedge_calculation.use_symmetry and not full_calculation.use_symmetry
    assert full_result.total_energy == pytest.approx(
        wedge_result.total_energy, abs=1e-9
    )

    wedge = compute_forces(wedge_calculation, wedge_result).forces
    full = compute_forces(full_calculation, full_result).forces
    assert np.abs(wedge - full).max() < 1e-6

    wedge_stress = compute_stress(wedge_calculation, wedge_result).tensor
    full_stress = compute_stress(full_calculation, full_result).tensor
    assert np.abs(wedge_stress - full_stress).max() < 1e-7


def test_a_displaced_spinor_cell_relaxes_back(pseudo_dir):
    """The relaxation is the BFGS that was already written, and needed nothing.

    ``pt2-soc-force`` is fcc platinum with one atom pushed 0.03 of the doubled
    lattice vector off its site, so the answer is known before the run: the two
    atoms have to end up half a cell apart. A smoke test rather than a
    comparison -- ``pw.x`` has no committed ``relax`` benchmark in this regime
    and generating one is a separate reference.

    **What is checked is the separation, not either position.** Subtracting the
    mean force leaves a rigid translation of the whole crystal free, and BFGS
    uses it: this run ends with both atoms moved 0.015 of a cell along ``a1``
    and 0.499945 apart. Asserting on an absolute coordinate would be asserting
    on which zero mode the optimizer happened to walk along.

    Achieved: converged in 8 ionic steps, ``max |F|`` 8.96e-5 Ry/bohr, the
    separation 5.5e-5 from a half.
    """
    system = build_system(read_pw_input(CASES / "pt2-soc-force.in"))
    pseudos = tuple(read_upf(pseudo_dir / s.pseudo_file) for s in system.structure.species)
    relaxed = run_relax(system, pseudos, conv_thr=1e-10, forc_conv_thr=1e-4,
                        etot_conv_thr=1e-6, nstep=15)
    assert relaxed.converged
    crystal = relaxed.positions @ np.linalg.inv(np.asarray(relaxed.system.cell.at))
    assert crystal[1, 0] - crystal[0, 0] == pytest.approx(0.50, abs=RELAX_POSITION)
    assert np.abs(relaxed.forces).max() < 1e-4


# --- what stays refused ------------------------------------------------------
#
# In ``tests/unit/test_spinor_refusals.py``, and **not** here, because a refusal
# fires on the *calculation* rather than on a converged state: three of the four
# need no SCF at all and the fourth needs one iteration, so they cost 13 seconds
# and belong in the fast gate. Left in this file they were slow-marked, and a
# refusal lifted by accident would have gone unnoticed until someone ran the
# two-hour set. The four are: the analytic force and stress expressions, which
# have no spinor form; ``energy_at``'s opt-in default, which is what keeps the
# elastic constants from inheriting a spinor path; the Sternheimer solver's own
# ``noncolin`` guard, which is a different missing term; and the force on an atom
# of a spin spiral.
